common/ayon_common/connection/credentials.py, common/ayon_common/connection/ui/__main__.py, common/ayon_common/connection/ui/login_window.py, common/ayon_common/utils.py, start.py
Login UI is running in subprocess.
Ayon executable can expect path to a script which will bypass standard cli processing. Also is possible to skip bootstrapping so login UI can actually start a script.
Login UI will be shown on start.
=> Run script: Login UI is running in subprocess

pyproject.toml, tools/runtime_dependencies.py
Added runtime dependencies required by openpype added to build for now.
Until we make a proper way how to defined and distribute them using addon definition these dependencies were added to installer base dependencies.
=> Runtime dependencies for openpype

setup.py
Use right filenames of icon files.
=> Setup: Fix icon filenames

tools/manage.ps1
Change poetry config to make sure venv is installed to the project.
Not sure if we should do the same for shell script?
=> Poetry venv installed to project

common/ayon_common/__init__.py, common/ayon_common/distribution/__init__.py, common/ayon_common/distribution/control.py, common/ayon_common/distribution/data_structures.py, common/ayon_common/distribution/downloaders.py, common/ayon_common/distribution/exceptions.py, common/ayon_common/distribution/file_handler.py, common/ayon_common/distribution/ui/installer_distribution_error.py, common/ayon_common/distribution/utils.py, common/ayon_common/utils.py, inno_setup.iss, poetry.lock, setup.py, start.py, tools/_runtime_deps.py, tools/build_post_process.py, tools/make.sh, tools/manage.ps1, tools/upload_to_server.py
Launcher using installer from bundle and auto-update logic. Prepared helper scripts and enhanced installer creation.
Build of ayon launcher will store information about it's path to file in user data so it is possible to find available versions of ayon executables by version. Distribution logic can handle requirements of different ayon-launcher versions. Implemented logic to store information about all available executables of ayon launcher (store the information on launch). So already installed versions can be found easily without need to install them. Implemented automated installation for Windows.
Better way how to get runtime dependencies and their versions using `pkg_packages` from build ayon launcher. Added helper script to upload installer to server. Changed `hash` to `checksum`.
- …
=> Installer distribution

common/ayon_common/distribution/control.py
Implemented auto-update logic for macOS dmg files.
The dmg file is mounted at the start and unmounted at the end. Once is mounted a file with `.app` extension is found which is copied to `/Applications`.
Once done a `Info.plist` is used to find executable that should be launched.
Follow instructions from https://github.com/ynput/ayon-launcher/pull/9 .
=> MacOs: Auto-update

start.py
Skip bootstrap directly jumps to script cli. Script cli processing does validate if passed file is a valid file for execution and raises appropriate exception.
=> More explicit main function

common/ayon_common/distribution/control.py
Don't use kwarg for `extract_archive_file`.
=> Fix linux auto-update

poetry.lock
Update ayon-python-api to 0.4.0.
=> Update ayon api

poetry.lock
Update ayon python api and acre to latest versions.
=> Release hotfixes

common/ayon_common/distribution/data_structures.py
Use `"url"` in http source instead of `"path"`.
=> Source: Fix http source type

poetry.lock
=> Update ayon python api

poetry.lock
Updated `ayon-python-api` to version 0.5.2.
=> Update ayon-python-api to 0.5.2

tools/manage.ps1
Make sure `build` folder exists before docker build.
The docker build fails if the folder does not exists.
=> Windows script fix

start.py
Print dev variant when dev bundle is used and add bundle name to printed information.
=> Chore: Print correct variant and bundle

poetry.lock
Updated ayon-python-api to 0.5.3.
=> Update ayon api to 0.5.3

tools/ayon_console.bat
I'm adding this file to be able to use my live ayon launcher in deadline. 
This can be considered redundant as we can use the following command, but it doesn't work in deadline. 
```
.\tools\manage.ps1 run
```
Everything should be working as usual. 
1. Test in command line
1. go to your cloned repo dir
2. run 
```
.\tools\ayon_console.bat
```
2. Test in Deadline, by adding the script path in deadline ayon plugin settings.
=> Enhancement: Add Ayon console bat

common/ayon_common/utils.py
Make sure AYON folder exists when site id file is created first time.
=> Make sure AYON folder exists when getting site id

poetry.lock
Update ayon api to '1.0.0-rc.3'.
=> Update ayon api to '1.0.0-rc.3'

start.py
Startup logic can handle login mode correctly when older ayon-launcher was used to launch new ayon launcher version.
Login mode was introduced in 1.0.1, when user launches e.g. version 1.0.0 which will, by bundle definition, relaunch to version 1.0.1. In that case `AYON_API_KEY` is set from 1.0.0 but `AYON_IN_LOGIN_MODE` is not set, so launcher will resolve as "not in login mode" which is incorrect assumption. This PR is handling cases when the first launched launcher version is before 1.0.1.
Question is if this PR makes sense as 1.0.1 still won't be able to handle it and at the time of 1.0.2 release will probably none of users use older ayon launchers.
1. Make a build and installer from this PR.
2. Upload it to server and use the version in your production bundle.
3. Launch older ayon …
=> Handle login mode when older launcher triggers launcher

poetry.lock
Changes after `poetry lock --no-update`.
=> Re-lock poetry

poetry.lock
Updated `ayon-python-api` and `certifi`.
Use newer versions of dependencies.
=> Chore: Update base dependencies

poetry.lock
Updated ayon-python-api to 1.0.9 .
=> Chore: Updated ayon-python-api to 1.0.9

poetry.lock, start.py
Updated ayon-python-api to 1.0.10.
Use new functions in ayon api to work with webaction events.
1. Make sure to run `./manage.ps1 create-env` to update dependencies.
2. AYON launcher should work ok.
3. Running webactions should work and should change status of event.
=> Chore: Update ayon api

poetry.lock, pyproject.toml
Updated ayon api to 1.1.1.
1. Run `./tools/manage.ps1 create-env`.
2. Launch AYON launcher (from code, or make a build).
3. All should be working as expected.
=> Chore: Updated ayon api

poetry.lock, pyproject.toml
=> Chore: Updated ayon python api

.dockerignore, .gitignore, tools/manage.ps1
Docker builds are stored into build folder named with the variant and pyside2 if enabled.
Helps to just run the docker builds one by one without being worried that existing build is being overriden.
=> Chore: Docker build enhancement

app_launcher.cpp
Add `AYON_PID_FILE` environment variable if `pid_file` is set in json. This affect linux and macOS application launcher when run from build.
1. build launcher on linux
2. execute script that is printing `AYON_PID_FILE`
=> Bug: add environment variable to track process id on linux
