common/ayon_common/distribution/control.py
common/ayon_common/distribution/data_structures.py

Quick fixed issues with dependency packages.
Use correct name of attributes, fill filename in sources, and use `"filename"` instead of `"name"` in attributes.

Dependency packages fixes

---

start.py

Pass `__file__` to executed script so the script can use it.
1. Run a script using ayon executable
```python
import os
print(os.abspath(__file__)
```
`./ayon_console.exe {path to script} --skip-bootstrap`
2. Output should print full path to a script

Scripts can access their file location

---

inno_setup.iss

Inno setup has new application ID instead of reusing id from OpenPype respotiory.
I forgot to change the application id when repository was created.

Windows: New application id in inno setup 

---

tools/build_post_process.py
tools/make.sh
tools/manage.ps1

Use pip freeze to get available package versions instead of reading poetry.lock.
Poetry lock does contain packages for all platforms which is unwanted, also pip freeze stores git repositories automatically without manually resolving them from poetry.lock.
1. Run build
2. Metadata about build should contain only dependencies that are really available in build and git repositories have git information

Better dependencies information

---

common/ayon_common/distribution/control.py
common/ayon_common/distribution/data_structures.py
start.py
tools/build_post_process.py

Finalized distribution of dependency packages once we have one ready.
Fixed DistributionItem creation for dependency package item. Renamed `name` to `filename` in dependency package item. Fixed OpenPype addon initialization in `main_cli` so vendorized modules are added to python and sys path. Build metadata file contains `"filename"`.
Prerequirements:
- Running AYON server 0.3.x
- Having at least `openpype` and `core` addons available
1. Build ayon-launcher
2. Upload installer to server
3. Create bundle with requested addons and new installer
4. Create dependency package for the bundle (using `ayon-dependencies-tool`)
5. Launch ayon-launcher
6. Validate it work
Note:
To make it fully work also add `ayon_third_party` and `ayon_ocio` addons and addons of your hosts for settings.

Distribution of dependency packages

---

tools/build_post_process.py
tools/make.sh
tools/manage.ps1

Force pip to not use colors when calling freeze.
Pip will use color characters during freeze, if has some available, which caused errors when parsing them. Changed how versions are split, instead of manual split is used regex.

Pip requirements fix

---

tools/build_post_process.py
tools/make.sh

Ayon-launcher can be built on macOS.
Remove cx_Freeze from dependencies directory which will keep cx_Freeze output lib. That works for all platforms because cx_Freeze is dependency that should not be propagated to any other process.
1. Build AYON on macOS
2. Run built application

MacOS build fix

---

start.py

Add `ayon_common` to PYTHONPATH properly.
There was a bug, wrong variables was used to add common to python path resulting in having dependencies path in PYTHONPATH twice and not having common there at all.

Start: Add common path to PYTHONPATH

---

README.md
tools/build_post_process.py
tools/installer_post_process.py
tools/make.sh
tools/manage.ps1

Modified make installer to create installer in subdir `build/installer/` which will contain installer file and metadata json ready for AYON server. Removed `create-server-package` command which does not have real usage for deployment.
Everything should work as before this PR.
1. Run `build` command
2. Run `make-installer` command
3. Run `upload` command
The only difference is that installer is nested subfolder `./build/installer/`.

Make installer script modification

---

inno_setup.iss

Path where application is installed should be filled correctly. Fix `/INSTALLDIR=...` logic.
The path always ended in local app data because it was the last option in code block (some Pascal condition logic).
1. Make installer
2. Run installer and choose to install for ALL USERS
3. Run installer and choose to install only locally
4. Run installer through command line and add custom install root `<installer path> /INSTALLROOt="C:\my custom\path"`

Windows: Install directory fill fix

---

tools/build_post_process.py

Installer uses sha256 checksum instead of md5.
Resolves https://github.com/ynput/ayon-launcher/issues/18

Change checksum algorithm sha256

---

start.py

Use correct environment variable to get bundle name in start.py.

Cosmetics: Bundle name is printed out

---

setup.py
tools/make.sh
tools/manage.ps1

MacOs build expected wrong version name in output filename because did not expect semver in version.py.
Added same approach how version is received to manage.ps1.
Build on macOs should work again.

Use correct AYON version

---

common/ayon_common/utils.py

Fixed issues with lookup for version of AYON launcher.
Stored launcher versions are validated once in 2 days. The validation happens automatically on launch. When existing version of AYON launcher is found out, the launcher must contain `version.py` with correct version -> in other word version in metadata has no value for automated lookup of AYON launcher versions. Cleanup function was fixed to work as expected.
The issue was that if anyone would start ayon from the same location and the launched version would not be demanded version by server, and the demanded version would point to the same executable, it would cause infinite start of ayon processes.
Hard to tell how to test. `%\Ynput\AYON\executables.json` should contain less informarmation if there was before more of them.

Executable version lookup fix

---

common/ayon_common/connection/credentials.py
common/ayon_common/distribution/README.md
common/ayon_common/utils.py

Use AYON launcher instead of AYON client in documentation.

Use AYON launcher in docstrings

---

common/ayon_common/distribution/control.py

Installer auto-update mechanism asks for permissions if target directory requires it. The auto-update crashes if process is executed in headless mode. If the process is running with admin permissions it should not ask for them anymore.
You will need to create 2 different versions of installer.
1. Create installer `beta.4` with this PR
2. Create installer `beta.5` (should not matter if has this PR)
3. Install `beta.4` to Program Files
4. Upload `beta.5` to server, set it to be used in a bundle, set the bundle as production
5. Run `beta.4`
6. An update should start which should ask for permissions if required

Windows auto-update: Ask for admin permissions when required

---

tools/build_post_process.py
tools/manage.ps1

Force to use utf-8 encoding when handling requirements.
This resolves issues when requirements file started with BOM (I couldn't replicate it).

Encoding issues during build

---

README.md
start.py
tools/manage.ps1

Bundle to use can be defined in command line arguments.
Added more information into readme about arguments and environment variables.
1. Use `ayon --bundle {your bundle name}`
2. It should start AYON with the bundle even if is not set as production (or staging).

Add bundle argument

---

tools/build_post_process.py

Change filename of created installer for macOs. Instead of `AYON-{version}-Installer.dmg` it is `AYON-{version}-macos.dmg`.
1. Try to build and make installer on MacOS
2. Ouptut installer should be named `AYON-{version}.macos.dmg`

Change output filename of macOs installer

---

app_launcher.py

Executable `app_launcher` fails with better message if did not get json filepath in argument.

Linux app launcher fails gracefully

---

Dockerfile.centos7
poetry.lock
pyproject.toml
tools/make.sh

Fixed copy of output from CentOS. Force poetry to lower `urllib3` version if OpenSSL version is lower than 1.1.1.
Define `urllib3` version that supports older OpenSSL in pyproject.toml. That is because most of DCCs are build with older ssl (e.g. Maya 2022, Nuke 13).
1. Run `./tools/make.sh docker-build centos7` (or `./tools/manage.ps1 docker-build centos7` for windows)
2. Check output

Docker build: CentOS build fixes

---

common/ayon_common/distribution/data_structures.py

Function 'prepare_sources' will log more information about unknown source.
At this moment it can happen with type `url` which is received by server for dependency packages. Just added title argument where caller sent to what it belongs.

Chore: More info for unknown sources

---

common/ayon_common/connection/credentials.py

Added custom implementation of 'is_token_valid' to be able to use service api key.
This way it is possible to launch ayon-launcher with service account which is needed for farm publishing or other automatization processes.
1. Set `AYON_SERVER_URL` environment to server and `AYON_API_KEY` to service api key
2. Start ayon launcher
3. It should start as usuall

Service api keys can be used to use launcher

---

Dockerfile.centos7

Docker build was missing `libssl.1.1.so` and `libcrypto.1.1.so` symlinks needed by the executable itself, because Python is now explicitly built with OpenSSL 1.1.1. This is similar to ynput/OpenPype#5633
This just creating symlinks, but to already copied libraries, but it should be probably handled more gracefuly.
- Build Centos 7 variant
- Run it on vanilla Centos 7 system

Centos build: Create symlinks for ssl libs

---

poetry.lock

Update `ayon-python-api` to `0.5.1` to add support for develop settings variants.

Update ayon-python-api to '0.5.1'

---

README.md
start.py
tools/manage.ps1

It is possible to show login on start of launcher.
Added `--ayon-login` argument flag which can trigger to show login dialog to change login before bootstrap.
1. Start ayon with `--ayon-login` argument
2. A login dialog should show asking to login

Add login argument

---

start.py

Set environment variable to define default settings variant.
The value can be used in non-ayon-launcher processes to define default variant without worrying when it should be set up (helpful in core > openpype addon).
Note: Core/openpype addon is handling that now by making sure a specific method in openpype.client.server is always called which may be dangerous in future. It is possible to use `ayon_api` before calling the function which may lead to incosistency. https://github.com/ynput/OpenPype/blob/develop/openpype/client/server/utils.py#L13 
This PR is based on update to ayon-api to 0.5.4 https://github.com/ynput/ayon-launcher/pull/72

Set env variable for settings variant

---

common/ayon_common/distribution/downloaders.py

Platform name is not used in `download_dependency_package` since ayon-python-api 0.3.x, and since last release is marked as deprecated.
1. Make sure bundle you're going to use have set dependency package.
2. Remove the dependency package from `%LOCALAPPDATA%/Ynput/AYON/dependency_packages/` if you have it downloaded already.
3. Run ayon-launcher with this PR (from code or build)
4. Download of dependency package should start.
5. It should download it just fine.

Platform name is not passed to 'download_dependency_package'

---

tools/manage.ps1

Make sure freeze content is without BOM by creating custom encoding object.
This can be validated only on machines where requirements were stored with BOM.

Make sure pip freeze content is without BOM

---

.dockerignore
.gitignore
common/ayon_common/distribution/control.py
pyproject.toml
tools/runtime_dependencies.py
vendor/README.md

Remove dependency packages that should be defined by ayon-core/openpype addon and use runtime dependencies from dependency package.
This PR will be combination of PRs in multiple repositories (OpenPype, ayon-dependencies-tool, ayon-launcher).
- [ayon-launcher](https://github.com/ynput/ayon-launcher/pull/78)
- [ayon-dependencies-tool](https://github.com/ynput/ayon-dependencies-tool/pull/9)
- [OpenPype](https://github.com/ynput/OpenPype/pull/6095)
1. Create ayon-launcher installer with this PR
2. Upload installer to server
3. Upload OpenPype addon with required change
4. Create a bundle with the installer and OpenPype addon
5. Create dependency package for the bundle and use it in the bundle
6. Run ayon-launcher with the bundle
7. All should be working

Runtime dependencies are based on dependency packages

---

tools/installer_post_process.py

Usage of `click` module was replaced by `argparse` and custom implementation. Click should not be included in ayon launcher dependencies.
The click was used only in helper script to create/upload installer on a server.

Removed requirement of click in ayon launcher

---

common/ayon_common/distribution/ui/missing_bundle_window.py
common/ayon_common/distribution/utils.py
start.py

Dialog shows username when dev bundle is not set. Prints when missing bundle will happen all the time.
1. Make sure you don't have set dev bundle
2. Start ayon launcher in dev mode
3. It should tell you that you don't have set dev bundle for your user

Missing dev bundle enhancements

---

setup.py

Ignore python builtin dependencies that are not available.
All the dependencies in the list are added "in advance" to match python dependencies, but are not required, and some of them are not available on some platforms, so we gracefully skip them.

Build process: Builtin python dependencies are added safely

---

common/ayon_common/utils.py
start.py

Set `AYON_SITE_ID` environment variable on start of ayon launcher.
Set the value so any future processes can use it without knowing where to find the information.
1. Launcher process from ayon-launcher have set `AYON_SITE_ID` if was not set before launching it.

Set AYON_SITE_ID environment variable on boot

---

common/ayon_common/connection/credentials.py
common/ayon_common/connection/ui/__init__.py
common/ayon_common/connection/ui/invalid_window.py
start.py

Define login mode in ayon launcher to be able determine if credentials are comming from keyring or were defined by environment variables.
Changes are implemented to avoid issues when ayon api key is defined with environment variable. In that case should not be possible to shown login UI, which would show different credentials (or unfilled window). In that case is shown Invalid credentials window with basic information. Login mode will also affect ayon tray. When user clicks on Login, the same dialog is shown.
Added more prints when things go wrong so we get more information, hopefully helpfull on render farm.
- Suggestion for env variable name `AYON_IN_LOGIN_MODE`.
- Suggestion for the message shown in dialog are welcomed.
- Different proposal for the solution?
1. Set env variables …

Login mode

---

common/ayon_common/distribution/control.py

Use only dev addons that have set version in the bundle.
It could happen that if a addon did not have set any version in dev bundle, but had set path to client code, it was added to sys path anyways.
There are no testing notes for this change. It's more about "correctness". I've discovered the bug when I had disabled `openpype` addon but set path to openpype when combined with `ayon-core` addon.

Addons in dev mode are used only if have set version

---

start.py

Bootstrap logic can use `ayon_core` addon over `openpype` as main cli handler.
This is forwards compatibility for `ayon-core` addon that will be released soon. The main difference is that ayon core will have `main` function that is called instead of directly working with click `main` command. That gives option to pass some of initialization steps from ayon-launcher to ayon-core addon, like change of PYTHONPATH and set-up global environments.
The changes should be backwards compatible with `openpype` addon.
1. Use ayon-core in your bundle.
2. Launch ayon-launcher with the bundle.
3. All should work fine.

Support ayon-core as main addon of startup logic

---

common/ayon_common/utils.py

First `sys.argv` may not be set correctly to `start.py` after bootstrap args manipulation. Using expicit path avoids possible issues.
1. Login dialog should show correctly when running from code and user is not logged in.

Use explicit path to start script instead of first `sys.argv`

---

tools/make.sh

Autofix issue with removing signature from ayon executable.
As I understood the issue: Codesign uses cache of executables, and when cx freeze is creating ayon executable it stores some cache that prevents from removing the signature. And removing the executable will clear the cache. So a copy of executable is created, then is removed the source executable to clear cache, and then is renameed the temp copy to the origin name. With this codesign does not crash.
1. Running `./tools/make.sh build` should work without any issues

MacOS build: Codesign auto fix

---

Dockerfile
tools/manage.ps1

Explicitly mention `"ubuntu"` in help text and allow to use `"ubuntu"` variant passed in as argument.

Mention ubuntu in docker build variants

---

tools/build_post_process.py
tools/make.sh
tools/manage.ps1

Requirements in installer json do contain correct git urls.
Since pip version 24, freeze does not seem to handle git urls, and stores filepath to source package instead. This PR uses combination of requirements from venv and export from poetry.
This is not ideal solution, but should be working.

Pip freeze fix

---

start.py

Content of `sys.argv` does not contain start.py script or ayon-launcher executable.
Reopened https://github.com/ynput/ayon-launcher/pull/94 . Changes in ayon-core were made and this change should be safe to do now.
This change might be done globaly in future PRs, now I'm too scared to do so.
1. Setup python script like below:
```python
import argparse
def main():
parser = argparse.ArgumentParser(description="Script description")
parser.add_argument(
"--something", type=str, required=True
)
args = parser.parse_args()
print(args.something)
if __name__ == "__main__":
main()
```
2. Run commandline to execute python script in AYON context:
```
.\tools\manage.ps1 run C:\Users\tokejepsen\Desktop\temp.py --something else
```
Error this PR fixes:
```
usage: start.py [-h] --something SOMETHING …
```

Remove first argument when running script

---

Dockerfile
Dockerfile.centos7
Dockerfile.debian
Dockerfile.rocky9
docs/build_guides/linux.md
pyproject.toml
tools/runtime_dependencies.py

Use PySide6 on all platforms.
Because centos 7 does not support latest versions of PySide6 it was necessary to keep it at PySide2.
- delete `vendor` in ayon-launcher
- run `ayon-launcher/tools/manage.ps1 install-runtime` 
1. Build on any affected platform (windows and linux distributions).
2. Install and run.
4. All UIs should work as expected.
(You could make sure you are running PySide6 in Tray > Admin > Console:
```
import PySide6
print(PySide6.__version__)
```
shouldnt fail and print 6.7.1 (on Windows)

Chore: Update to PySide6

---

setup.py

Enable `include_msvcr` to include `vcruntime140.dll` in build.
Some windows distributions don't have the dll by default.

Windows build: Enable 'include_msvcr'

---

poetry.lock
pyproject.toml

Updated ayon-python-api to 1.0.7 and unidecode to 1.3.8 which is required by newer versoin of ayon-python-api.

Chore: Update ayon python api

---

common/ayon_common/distribution/control.py

Don't consider empty `AYON_BUNDLE_NAME` environment variable as defined bundle name.
This issue was discovered during testing of deadline jobs. GlobalPreLoadJob.py does set bundle name based on job environment variables, but if that is not filled it does fill empty string `""` and because deadline api does not support to "remove env key" (at least I didn't find it) this was the best solution. But at the end, it is not just fixing issue because of deadline, but fixing issue discovered thanks to deadline.

Chore: Ignore empty value of 'AYON_BUNDLE_NAME' env variable

---

common/ayon_common/distribution/control.py

Don't fetch addon information with details.
We're getting addons with all details which are not used, but the speed difference is significant (at about 0.8 seconds).
1. Bootstrap should be a little bit faster.

Distribution: Don't use addon details

---

common/ayon_common/_windows_register_scheme.py
common/ayon_common/utils.py
inno_setup.iss
shim/ayon.desktop
start.py

AYON launcher is capable of handling `ayon-launcher` scheme using shims.
AYON launcher is handling `ayon-launcher` scheme. On all platfrorms is the handling done using shim as startup executable. This way we have only one executable registered for handling of the scheme without being worried about different AYON launcher versions.
On macOs is scheme defined in shim's plist. On linux we use `ayon.desktop` which is also used for showing shortcut in apps menu. On windows is necessary to register the scheme, for that is necessary to have admin privileges and installation of shims will ask for them. At this moment this happens only on first shim installation, and there is no easy way how to register it afterwards.
We can prepare .reg file for windows admins so they can easily deploy and …

WebActions: Launcher can handle webactions

---

common/ayon_common/distribution/control.py

Revert https://github.com/ynput/ayon-launcher/pull/130 which stopped to use details.
Details is important to get information about client files from server.
1. AYON launcher should update client code.

Chore: Use addons details

---

common/ayon_common/connection/credentials.py
common/ayon_common/distribution/control.py
common/ayon_common/distribution/utils.py
common/ayon_common/utils.py

Use `exist_ok=True` when `os.makedirs` is called.
Simplifies the code and also makes it more safe.
1. AYON launcher is capable of creating all folders that are necessary to be created.

Chore: Use 'exist_ok' when directory is created

---

tools/make.sh
tools/manage.ps1

Manage.ps1 and make.sh scripts do not rely on `POETRY_HOME` environment variable but always use relative path to repository.
The scripts did rely on the environment variable value and did set the variable only if was not set already. If there is global env variable set for user, or user have terminal which has set the env variable from different script it uses wrong path which leads to confusion and potentially broken environment.
The environment variable is set only when create-env is called to define target path, which is not possible with arguments.
1. Remove `./.poetry/` with it's content (and `./.venv/`).
2. Open terminal and set env variable `POETRY_HOME` to some random directory.
3. Run `./manage.ps1 create-env` on windows or `./make.sh create-env` on linux/macOs
4. It should …

Chore: Scripts don't rely on POETRY_HOME env variable

---

docs/build_guides/macos.md

Added information about rosetta virualization to build docs.
We do require rosetta virualization to be able to build AYON launcher on macOs. Which is missing piece of information in docs.

Docs: Add rosetta virualization to docs

---

common/ayon_common/connection/ui/login_window.py
common/ayon_common/resources/stylesheet.css

Show password button is not triggered on Enter press. All buttons have disabled "default" handling of Enter press, all enter presses are handled manually. Enter press in url input will trigger login using AYON server instead of going to Username input. Added focus style to buttons.
Also added explicit margins and spacing definition to "fix" margins and spacing on other than windows platform.
1. Enter press in password input does not reveal password.
2. Focused button is highligted.

Login window: Enhancements and fixes

---

tools/build_post_process.py
tools/make.sh
tools/manage.ps1
tools/runtime_dependencies.py

Installer filename contains information about used pyside2 and on linux also contains distribution short .
It is PITA to find out for which distribution was laucher created and if was created with pyside2 or pyside6, this should help a little. Server still does support only one linux installer, but at least we're able to find out which is used.
1. Create linux installer.
2. Filename should automatically contain distro name.
3. If `--use-pyside2` is used, the filename also contains `-pyside2`.
Resolves https://github.com/ynput/ayon-launcher/issues/128

Chore: Add distro and pyside2 information to installer filename

---

common/ayon_common/utils.py

Skip desktop distribution if applications dir does not exist.
Applications dir does not exist on headless distrubtions, which caused crashes.
1. Make linux build.
2. Run it on headless linux distribution.
3. It should not crash.

Shim: Fix deployment on headless linux

---

docs/build_guides/macos.md

Adds [create-dmg](https://formulae.brew.sh/formula/create-dmg) as a Brew dependency in the build requirements on MacOS.
This is needed during the build phase:
https://github.com/ynput/ayon-launcher/blob/develop/tools/build_post_process.py#L183
1. Follow the [MacOS build instructions](https://github.com/ynput/ayon-launcher/blob/develop/docs/build_guides/macos.md)

Macos: add create-dmg in build requirements

---

poetry.lock
pyproject.toml

pip 24.1 dropped support for Python 3.7. This PR is freezing pip to 24.0. 
Pip is used when installing/querying packages like if pyside2/6 is installed.
Re-create situation, where Python 3.7 based host tries to install pyside in their pre-launch hooks.

🧊 freeze pip to version still supporting python 3.7

---

README.md
common/ayon_common/_windows_register_scheme.py

Register scheme handler under CURRENT_USER registry to avoid requirement for admin privileges and to avoid issues connected to multi-user machine.
Modification of `HKEY_CURRENT_USER\SOFTWARE\Classes` does not require admin privileges and adding `ayon-launcher` there has same effect as in `HKEY_CLASSES_ROOT`.
User classes have bigger priority over `HKEY_CLASSES_ROOT` so it should work even if machine already has set up `ayon-launcher` in `HKEY_CLASSES_ROOT`.
1. Open `regedit` tool (Win + R -> type "regedit" -> Enter) and remove `ayon-launcher` from `HKEY_CLASSES_ROOT` (ignore this step if is not there).
2. Build and make installer from this branch.
3. Upload and install the installer on your machine.
4. Start webaction (e.g. application) from AYON server.
5. Application should be starting. …

Scheme handler: Windows scheme handler does not need admin privileges

---

start.py

Handle status of webactions and pass the event id via `AYON_WEBACTION_EVENT_ID` enviornment variable. Launcher logic makes sure status is set to failed/finished if is still in progress at the end of process, and will abort action if user skips login logic.
Pass event id of webaction to children AYON launcher process so he can try to handle it via `AYON_WEBACTION_EVENT_ID`.
- Requires https://github.com/ynput/ayon-backend/pull/386 to change status at the end of process
- Requires https://github.com/ynput/ayon-backend/pull/387 to change status on skip login
1. Build AYON launcher and create installer.
2. Upload installer to server.
3. Use the version in your bundle.
4. Launch webaction.
5. Status of webaction should change to finished or failed, based on what happened.
Important note: It …

Webaction: Handle event status

---

common/ayon_common/utils.py
start.py

Make sure that windows registry is set to new registry path on update.
Windows registry are not updated if shim is already deployed, changes in this PR makes sure windows registry are updated on launcher update.
1. Checkout this branch and build AYON launcher.
2. Install 1.1.0 AYON launcher and confirm admin privileges -> that should install shim and register protocol.
3. Install launcher from this branch.
4. When installation is finished, registry `HKEY_CURRENT_USER\SOFTWARE\Classes\ayon-launcher` should be set.

Chore: Installing of new AYON launcher makes sure windows registry is set

---

common/ayon_common/distribution/__init__.py
common/ayon_common/distribution/control.py
common/ayon_common/distribution/ui/distribution_error.py
common/ayon_common/distribution/utils.py
common/ayon_common/utils.py
start.py

Modified distribution to be able to handle missing permissions in destination directory. A dialog is shown if user does not have permissions to distribute installer, addons or dependency package. If everything is available, then it just uses it.
Make sure that folders are not created if they already do exist, because it can trigger `PermissionsError`.
Windows should not be affected at all.
1. Create a directory with read permissions for other users (e.g. `/usr/share/ayon`).
2. Create "artist" user (you have to set password to the user).
1. Open terminal and use the user (`su - artist`)
2. Set env variable `AYON_LAUNCHER_STORAGE_DIR` to dir from `General setup 1`.
3. Start AYON launcher with changes from this PR.
4. It should show dialog that you don't have permissions.
5. As sudo: Start …

Chore: Safe distribution

---

common/ayon_common/distribution/control.py

Set new executable path on AYON launcher update on macOs.
1. Automated update of AYON launcher on macOs does work.

macOs: Fix executable path on update

---

common/ayon_common/distribution/control.py
common/ayon_common/distribution/data_structures.py
common/ayon_common/distribution/downloaders.py
common/ayon_common/distribution/file_handler.py
common/ayon_common/distribution/tests/test_addon_distributtion.py

Use `dataclasses` instead of `attrs` for data holder classes in distribution logic.
1. Make sure you have things to distribute, at least one addon and dependency package -> You can remove them in appdirs for full distribution.
2. Run AYON launcher with this PR.
3. Distribution should be successful.

Chore: Use dataclasses in distribution logic

---

poetry.lock
pyproject.toml
shim/poetry.lock
shim/pyproject.toml

Use `tool.poetry.group.dev.dependencies` instead of `tool.poetry.dev-dependencies`.
Group `tool.poetry.dev-dependencies` is being deprecated.

Chore: Use poetry dev group

---

tools/make.sh

pip version 24.1 and higher is not compatible with Python 3.7 hosts. We've freezed the version in #175 but we were still force-updating pip in the make/manage script when creating environment on Linux
- Build launcher
- Use it to run in some python 3.7 host (Maya 2020, 3dequalizer4 v7, ...)

Remove forced pip update

---

README.md
common/ayon_common/distribution/__init__.py
common/ayon_common/distribution/utils.py
start.py

Distribution can be skipped or blocked if something is missing using environment variable `AYON_AUTO_UPDATE`.
If the environment variable is set to `skip`, then any missing item to distribute (AYON laucher, addon, dependency package) will be skipped .
1. Remove an addon (e.g. maya) from addons dir.
2. Set env variable `AYON_AUTO_UPDATE` to `"skip"` (`$env:AYON_AUTO_UPDATE="skip"` in powershell).
3. Run AYON launcher.
4. Addon should not be distributed but AYON should launch ok (if is not missing crutial addon).
5. Close the progress.
6. Set env variable `AYON_AUTO_UPDATE` to `"block"` (`$env:AYON_AUTO_UPDATE="block"` in powershell).
7. Run AYON launcher.
8. A dialog should pop up with information that update is required but auto-update is blocked.
9. Unset the env …

Chore: Allow to skip or block auto update

---

common/ayon_common/distribution/data_structures.py

Fix wrong assignment instead of type annotation.
1. Installer initialization doesn't fail.

Chore: Fix attribute error in Installer

---

common/ayon_common/distribution/control.py

Try to catch possible issues that may happen during movement of unzipped directory.
Issue that can happen during distribution. Metadata file `addons.json` has invalid content or is missing and `dist_progress.json` file in addon has invalid content or is missing. In that case the addon folder does exists and may have correct content but distribution logic cannot tell. So it tries to distribute it, but fails on movement of unzipped content.
Solution is to first make sure that any existing content in target directory is temporarily moved to different folder. Then try to move new content. If any of that fails then remove any content that was moved and rename any content that was renamed to previous state. If it fails it also makes sure that the temp download directory is cleaned up.
1. Go to …

Distribution: Unzipped content move is guarded

---

poetry.lock
pyproject.toml

Remove dependencies needed for docs build to support older python versions.
Dependencies added for docs build did break some DCC versions because they still use older python version.
For example `ftrack_api` does import `pyparsing` which is using syntax available from python 3.9
PR which added the dependencies https://github.com/ynput/ayon-launcher/pull/209 .
1. Remove `.venv` in root (if you have any).
2. Run `./tools/manage.ps1 create-env`.
3. Run AYON launcher.
4. AYON launcher can be used in older DCCs (like Nuke 13).

Chore: Revert dependencies for docs build

---

app_launcher.cpp

Do not wait for spawned process to end and dispatch stdout and stderr.
1. When traypublisher or dcc is launched on linux, it does not cause stuck of the process from which it was triggered.

Linux: App launcher don't wait for process to end

---

common/ayon_common/distribution/control.py

Trigger `finish_distribution` even if anything fails.
Finish distribution method is important to do as it marks distributed addons, dependency packages and does cleanup temporary folders, which is important even if other parts of distribution failed.
1. You can break AYON launcher with Ctrl + C during distribution, but it should cleanup all folders.

Distribution: Make sure to trigger finish distribution

---

common/ayon_common/distribution/control.py

Make move after extraction faster by using `os.rename` instead of `shutil.move`.
To make sure we can call `os.rename` the files are not extracted to download directory which lives in `%TEMP%` but to directory next to addons and dependency packages, so we're sure we can safely use OS rename functionality.
This makes it even more complicated but should enhance speed for slower file systems.
To validate this change you need setup where you can see that the difference in distribution speed is slower that e.g. with AYON launcher 1.1.1 .

Distribution: Faster move of files to target directory

---

Dockerfile.rocky8

Use older Rocky 8 image which is usually used by VFX studios.

Docker build: Use Rocky 8.5 image

---

common/ayon_common/distribution/control.py

Try to avoid possible permissions issues with temp directories.
Make sure that created temp directories have `777` permissions so other users can clean it up. It is common that linux machine uses different users, e.g. one for farm and one for artist, in that case they can't cleanup temp directories which might be blocking.
I don't know how to test. The most important part is that `/tmp/ayon_dist_downloads` has `777` mode permissions instead of `775`.

Chore: Avoid permissions issues

---

app_launcher.cpp
app_launcher.py

Store PID of launched process back to the json file.
The PID is important part of information that is not used at this moment but will be in near future.
1. Build AYON launcher, upload to server and use it in a bundle.
2. Applications can be launched from AYON launcher or webactions.
3. The json file will contain the pid.

App launcher: Store pid of launched process back to the json file

---

common/ayon_common/distribution/control.py

Ignore project bundle name if is same as studio bundle.
If project bundle is not defined then it is filled with studio bundle name. On subprocess launch is the bundle tried to be found as project bundle leading to crashes.
```
Traceback (most recent call last):
File "~\ayon\ayon-launcher\start.py", line 1152, in <module>
main()
File "~\ayon\ayon-launcher\start.py", line 1142, in main
boot()
File "~\ayon\ayon-launcher\start.py", line 787, in boot
_start_distribution()
File "~\ayon\ayon-launcher\start.py", line 597, in _start_distribution
project_bundle = distribution.project_bundle_to_use
File "~\ayon\ayon-launcher\common\ayon_common\distribution\control.py", line 1766, in project_bundle_to_use
project_bundle = self._get_project_bundle()
File …
```

Project bundles: Fix fetch of project bundle

---

app_launcher.cpp
app_launcher.py

App laucher can pass stdout and stderr paths from the json file. Or allows to not change stdout and stderr if json explicitly tells to not to.
1. App launcher works.
1. Prepare testing json file.
2. Add `"stdout"` and `"stderr"` with paths to custom paths.
3. Run applauncher with path to the json file.
4. The stdout and stderr files are used.

App launcher: Allow to pass in stdout and stderr paths

---

poetry.lock
pyproject.toml

Updated ayon python api to `1.2.1`.
1. Launcher still works.

Chore: Update ayon python api to '1.2.1'

---

start.py

Use `--bundle` to specify studio bundle and replace `--studio-bundle` with `--project-bundle`.
Using `--bundle` for project bundle did not make sense. There was also a bug -> using `----studio-bundle` instead of `--studio-bundle` string leading to crashes if was used.
This change also makes it work more as it did work before 1.4.0 release.
1. Using `--bundle` will define which studio bundle is used.

Chore: Change bundle arguments handling
